In [64]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [65]:
import numpy as np

def grayscale_image( height, width):
  np.random.seed(0)
  return np.random.randint(0, 255, (height, width), dtype=np.uint8)

In [66]:
def embed_to_image(image_matrix, key):
  binary_key = key + '1111111111111110' # delimiter to mark end
  print("Binary_key:", binary_key)
  data_index = 0
  stego_image = image_matrix.copy()

  height, width = image_matrix.shape

  for i in range(height):
    for j in range(width):
      if data_index < len(binary_key):
        stego_image[i,j] = (stego_image[i,j] & 0xFE) | int(binary_key[data_index])
        data_index +=1
      else:
        return stego_image

In [67]:
def extract_key(image_matrix):
    binary_key = ''
    height, width = image_matrix.shape

    for i in range(height):
        for j in range(width):
            binary_key += str(image_matrix[i,j] & 1)

    delimiter = '1111111111111110'
    binary_key = binary_key[:binary_key.find(delimiter)]
    print("binary_key:",binary_key)
    return binary_key

In [68]:
def restore_image(stegno_image):
    restore_imaage = stegno_image.copy()
    height, width = stegno_image.shape

    for i in range(height):
        for j in range(width):
            restore_imaage [i,j] = restore_imaage[i,j] & 0xFE
    return restore_imaage

In [69]:
original_matrix = grayscale_image(5,5)
key = '01000001'

In [70]:
print("image", original_matrix)

image [[172  10 127 140  47]
 [170 196 151 117 166]
 [ 22 183 192 204  33]
 [216  67 179  78 154]
 [251  82 162 219 195]]


In [71]:
stegno_image = embed_to_image(original_matrix,key)

Binary_key: 010000011111111111111110


In [72]:
print("Stegno_image")
print(stegno_image)

Stegno_image
[[172  11 126 140  46]
 [170 196 151 117 167]
 [ 23 183 193 205  33]
 [217  67 179  79 155]
 [251  83 163 218 195]]


In [73]:
extract_key = extract_key(stegno_image)

binary_key: 01000001


In [74]:
print("key:", extract_key)

key: 01000001


In [75]:
restored_image = restore_image(stegno_image)

In [76]:
print("Restored image:")
print(restored_image)

Restored image:
[[172  10 126 140  46]
 [170 196 150 116 166]
 [ 22 182 192 204  32]
 [216  66 178  78 154]
 [250  82 162 218 194]]


In [77]:
print("Original Matrix:")
print(original_matrix)
print("\n\n")
print("Stegno Matrix:")
print(stegno_image)
print("\n\n")
print("Restored Matrix:")
print(restored_image)




Original Matrix:
[[172  10 127 140  47]
 [170 196 151 117 166]
 [ 22 183 192 204  33]
 [216  67 179  78 154]
 [251  82 162 219 195]]



Stegno Matrix:
[[172  11 126 140  46]
 [170 196 151 117 167]
 [ 23 183 193 205  33]
 [217  67 179  79 155]
 [251  83 163 218 195]]



Restored Matrix:
[[172  10 126 140  46]
 [170 196 150 116 166]
 [ 22 182 192 204  32]
 [216  66 178  78 154]
 [250  82 162 218 194]]
